Fix handling of public/.git when zola build fails

diff --git a/build b/build
--- a/build
+++ b/build
@@ -18,11 +18,23 @@ fi
 # Save .git/
 mv public/.git tmp
 
+# Disable exit on error
+set +e
+
 # Build the website. This deletes public/ if it exists.
 zola build
 
+# Save the exit code for checking later.
+STATUS=$?
+
+# Re-enable exit on error
+set -e
+
 # Restore .git/
 mv tmp public/.git
+
+# Exit if zola build failed.
+if (( $STATUS )); then exit 1; fi
 
 # Show the repository status
 cd public
@@ -32,6 +44,7 @@ if [ -z "$CHANGES" ]; then
 else
   echo "Changes found:"
   echo "$CHANGES"
-  echo "Run ./push.sh"
+  echo
+  echo "If you're happy with the changes, run ./deploy"
   exit 1
 fi
